name: shared_preferences_android
description: Personalized Android implementation of the shared_preferences plugin
repository: https://github.com/OscarDavidAngarita/plugins-test/tree/main/packages/shared_preferences/shared_preferences_android

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      android:
        package: io.flutter.plugins.sharedpreferences
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesAndroid

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
